return {
	-- SADNESS LINEAGE
	Weeper = {
		name = "Weeper",
		emotion = "Sadness",
		rarity = "Common",
		level = 1,
		description = "A tiny teardrop blob. Pale blue.",
		baseOutput = 1.0,
		dropSound = "Sadness",
	},
	Glumpling = {
		name = "Glumpling",
		emotion = "Sadness",
		rarity = "Uncommon",
		level = 2,
		description = "Big watery eyes. Sighs constantly.",
		baseOutput = 1.0,
		dropSound = "Sadness",
	},
	Soaker = {
		name = "Soaker",
		emotion = "Sadness",
		rarity = "Rare",
		level = 3,
		description = "Waterlogged, always dripping.",
		baseOutput = 1.0,
		dropSound = "Sadness",
	},
	Cryo = {
		name = "Cryo",
		emotion = "Sadness",
		rarity = "Epic",
		level = 4,
		description = "Frozen solid. Ice crystallizes around it.",
		baseOutput = 1.0,
		dropSound = "Sadness",
	},
	Abyssal = {
		name = "Abyssal",
		emotion = "Sadness",
		rarity = "Legendary",
		level = 5,
		description = "Absorbs all light around it.",
		baseOutput = 1.0,
		dropSound = "Sadness",
	},

	-- RAGE LINEAGE
	Ember = {
		name = "Ember",
		emotion = "Rage",
		rarity = "Common",
		level = 1,
		description = "Small sparking blob. Always trembling.",
		baseOutput = 1.0,
		dropSound = "Rage",
	},
	Furon = {
		name = "Furon",
		emotion = "Rage",
		rarity = "Uncommon",
		level = 2,
		description = "Shaking with rage. Eyes on fire.",
		baseOutput = 1.0,
		dropSound = "Rage",
	},
	Scorcher = {
		name = "Scorcher",
		emotion = "Rage",
		rarity = "Rare",
		level = 3,
		description = "Lava cracks cover its body.",
		baseOutput = 1.0,
		dropSound = "Rage",
	},
	Inferno = {
		name = "Inferno",
		emotion = "Rage",
		rarity = "Epic",
		level = 4,
		description = "Surrounded by a heat haze.",
		baseOutput = 1.0,
		dropSound = "Rage",
	},
	Pyroclast = {
		name = "Pyroclast",
		emotion = "Rage",
		rarity = "Legendary",
		level = 5,
		description = "Walking eruption. Ground cracks beneath it.",
		baseOutput = 1.0,
		dropSound = "Rage",
	},

	-- JOY LINEAGE
	Sparklet = {
		name = "Sparklet",
		emotion = "Joy",
		rarity = "Common",
		level = 1,
		description = "Tiny bouncing blob. Can't stop moving.",
		baseOutput = 1.0,
		dropSound = "Joy",
	},
	Sunkling = {
		name = "Sunkling",
		emotion = "Joy",
		rarity = "Uncommon",
		level = 2,
		description = "Fat round blob with jazz hands.",
		baseOutput = 1.0,
		dropSound = "Joy",
	},
	Radiant = {
		name = "Radiant",
		emotion = "Joy",
		rarity = "Rare",
		level = 3,
		description = "Glows so bright it hurts to look at.",
		baseOutput = 1.0,
		dropSound = "Joy",
	},
	Solaris = {
		name = "Solaris",
		emotion = "Joy",
		rarity = "Epic",
		level = 4,
		description = "Miniature sun orbits around it.",
		baseOutput = 1.0,
		dropSound = "Joy",
	},
	Luminar = {
		name = "Luminar",
		emotion = "Joy",
		rarity = "Legendary",
		level = 5,
		description = "Pure light given form.",
		baseOutput = 1.0,
		dropSound = "Joy",
	},

	-- DREAD LINEAGE
	Shiver = {
		name = "Shiver",
		emotion = "Dread",
		rarity = "Common",
		level = 1,
		description = "Tiny trembling blob. Hides its face.",
		baseOutput = 1.0,
		dropSound = "Dread",
	},
	Lurk = {
		name = "Lurk",
		emotion = "Dread",
		rarity = "Uncommon",
		level = 2,
		description = "Whispers to itself. Wide toothy mouth.",
		baseOutput = 1.0,
		dropSound = "Dread",
	},
	Phantom = {
		name = "Phantom",
		emotion = "Dread",
		rarity = "Rare",
		level = 3,
		description = "Invisible except for its eyes.",
		baseOutput = 1.0,
		dropSound = "Dread",
	},
	Specter = {
		name = "Specter",
		emotion = "Dread",
		rarity = "Epic",
		level = 4,
		description = "Passes through walls. Leaves cold spots.",
		baseOutput = 1.0,
		dropSound = "Dread",
	},
	Eclipse = {
		name = "Eclipse",
		emotion = "Dread",
		rarity = "Legendary",
		level = 5,
		description = "Half blinding white, half void black.",
		baseOutput = 1.0,
		dropSound = "Dread",
	},

	-- VOID LINEAGE
	Mote = {
		name = "Mote",
		emotion = "Void",
		rarity = "Common",
		level = 1,
		description = "A tiny speck of nothing.",
		baseOutput = 1.0,
		dropSound = "Void",
	},
	Nullling = {
		name = "Nullling",
		emotion = "Void",
		rarity = "Uncommon",
		level = 2,
		description = "Black hole eyes. Floats silently.",
		baseOutput = 1.0,
		dropSound = "Void",
	},
	Rift = {
		name = "Rift",
		emotion = "Void",
		rarity = "Rare",
		level = 3,
		description = "Tears in its body show other dimensions.",
		baseOutput = 1.0,
		dropSound = "Void",
	},
	Sunder = {
		name = "Sunder",
		emotion = "Void",
		rarity = "Epic",
		level = 4,
		description = "Reality warps around it.",
		baseOutput = 1.0,
		dropSound = "Void",
	},
	Null = {
		name = "Null",
		emotion = "Void",
		rarity = "Legendary",
		level = 5,
		description = "The absence of everything.",
		baseOutput = 1.0,
		dropSound = "Void",
	},

	-- NOSTALGIA LINEAGE
	Wisp = {
		name = "Wisp",
		emotion = "Nostalgia",
		rarity = "Common",
		level = 1,
		description = "Faded pastel blob. Hums quietly.",
		baseOutput = 1.0,
		dropSound = "Nostalgia",
	},
	Reminisce = {
		name = "Reminisce",
		emotion = "Nostalgia",
		rarity = "Uncommon",
		level = 2,
		description = "Old-timey moustache. Looks slightly faded.",
		baseOutput = 1.0,
		dropSound = "Nostalgia",
	},
	Reverie = {
		name = "Reverie",
		emotion = "Nostalgia",
		rarity = "Rare",
		level = 3,
		description = "Old photographs drift around it.",
		baseOutput = 1.0,
		dropSound = "Nostalgia",
	},
	Chronos = {
		name = "Chronos",
		emotion = "Nostalgia",
		rarity = "Epic",
		level = 4,
		description = "Ages whatever it touches.",
		baseOutput = 1.0,
		dropSound = "Nostalgia",
	},
	Eternity = {
		name = "Eternity",
		emotion = "Nostalgia",
		rarity = "Legendary",
		level = 5,
		description = "A living memory of everything.",
		baseOutput = 1.0,
		dropSound = "Nostalgia",
	},

	-- MYTHIC TIER (no lineage, standalone)
	TheWatcher = {
		name = "The Watcher",
		emotion = "Any",
		rarity = "Mythic",
		level = 6,
		description = "Produces nothing. During any boost: 50x output.",
		baseOutput = 0,
		watcherMultiplier = 50,
		dropSound = "Mythic",
	},
	Unknown = {
		name = "???",
		emotion = "Unknown",
		rarity = "Mythic",
		level = 6,
		description = "Nobody knows what this is.",
		baseOutput = 1.0,
		dropSound = "Mythic",
	},
	VoidNull = {
		name = "Null",
		emotion = "Void",
		rarity = "Mythic",
		level = 6,
		description = "White vial. No sound. No particles.",
		baseOutput = 1.0,
		dropSound = "Silence",
	},

	-- EVENT STATION EXCLUSIVES (Phase 17) -- isEventExclusive keeps these out of
	-- RollTable.RollMonsterOfRarity's standard-roll pool; only purchasable with
	-- Event Tokens via EventStation.PurchaseEventMonster.
	Glitchling = {
		name = "Glitchling",
		emotion = "Static",
		rarity = "Rare",
		level = 3,
		description = "Event Station exclusive. Flickers between frames of reality.",
		baseOutput = 1.0,
		dropSound = "Static",
		isEventExclusive = true,
	},
	Voidborn = {
		name = "Voidborn",
		emotion = "Void",
		rarity = "Epic",
		level = 4,
		description = "Event Station exclusive. Born from the space between servers.",
		baseOutput = 1.0,
		dropSound = "Void",
		isEventExclusive = true,
	},
	Prismatic = {
		name = "Prismatic",
		emotion = "Any",
		rarity = "Legendary",
		level = 5,
		description = "Event Station exclusive. Refracts every emotion at once.",
		baseOutput = 1.0,
		dropSound = "Mythic",
		isEventExclusive = true,
	},
	Corrupted = {
		name = "Corrupted",
		emotion = "Any",
		rarity = "Legendary",
		level = 5,
		description = "Event Station exclusive. Data that shouldn't exist.",
		baseOutput = 1.0,
		dropSound = "Mythic",
		isEventExclusive = true,
	},
	Hollow = {
		name = "Hollow",
		emotion = "Sadness",
		rarity = "Epic",
		level = 4,
		description = "Event Station exclusive. An echo of something that used to feel.",
		baseOutput = 1.0,
		dropSound = "Sadness",
		isEventExclusive = true,
	},
}
